//GET http://localhost:4000/users

//GET http://localhost:4000/users/1be663ad-1bf6-414a-8b16-3152cbc926ef

# POST http://localhost:4000/users
# Content-Type: application/json

# {
#   "firstname": "Laura",
#   "lastname": "Segouras",
#   "email": "lausegouras@gmail.com",
#   "password": "123456",
#   "confirmpassword": "123456"
# }

//DELETE http://localhost:4000/93bce043-e7b1-4999-a08f-60db49b0ccd1

POST http://localhost:4000/auth/login

Content-Type: application/json

{
  "email": "lsegouras@gmail.com",
  "password": "123@Laura"
}